spring:
    application:
        name: mobi7-vehicle-stay-time-be
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost/postgres}
        username: ${DB_USER:postgres}
        password: ${DB_PASSWORD:root}

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: false
    flyway:
            baseline-on-migrate: true
            baseline-version: 0
            clean-on-validation-error: true
            clean-disabled: false
server:
    port: 8080
mob7feign:
        name: mob7
        name-pos: mob7-position
        url: https://challenge-backend.mobi7.io/

springdoc:
    swagger-ui:
        path: /swagger-ui.html